version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:password@db:5432/mentor
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mentor_test
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_PATH=./data/chroma
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - DEBUG=true
      - RELOAD=true
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - chroma
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mentor
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/chroma
